#if !defined (RDYCORECOREDEF_H)
#define RDYCORECOREDEF_H

#define CONDITION_DIRICHLET        0
#define CONDITION_NEUMANN          1
#define CONDITION_REFLECTING       2
#define CONDITION_CRITICAL_OUTFLOW 3

#endif
