// NOTE: This self-contained header was generated by CMake from
// NOTE: include/private/physics_ceed.h.in. It allows the JIT compiler access to
// NOTE: information needed for building Q-functions using GPU backends.
// NOTE: PLEASE DO NOT EDIT DIRECTLY! Instead, make any necessary changes to
// NOTE: include/private/physics_ceed.h.in.

#ifndef SEDIMENT_CEED_H
#define SEDIMENT_CEED_H

#include <ceed/types.h>

#define MAX_NUM_FIELD_COMPONENTS   8

// material properties
#define MATERIAL_PROPERTY_MANNINGS 0
#define NUM_MATERIAL_PROPERTIES    1

// sediment dynamics
#define MAX_NUM_SEDIMENT_CLASSES   5

// convenience macros

#ifndef Square
#define Square(x) ((x) * (x))
#endif

#ifndef SafeDiv
#define SafeDiv(a, b, c, tiny) ((c) > (tiny) ? (a) / (b) : 0.0)
#endif

#endif
