# CMake generated Testfile for 
# Source directory: /Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment
# Build directory: /Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/sediment
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sediment_mms_conv_study_c_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms" "sediment_mms_conv_study.yaml")
set_tests_properties(sediment_mms_conv_study_c_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;17;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_mms_conv_study_f90_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms_f90" "sediment_mms_conv_study.yaml")
set_tests_properties(sediment_mms_conv_study_f90_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;17;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_mms_conv_study_c_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms" "sediment_mms_conv_study.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_mms_conv_study_c_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;17;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_mms_conv_study_f90_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms_f90" "sediment_mms_conv_study.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_mms_conv_study_f90_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;17;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_upwind_mms_conv_study_c_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms" "sediment_upwind_mms_conv_study.yaml")
set_tests_properties(sediment_upwind_mms_conv_study_c_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;28;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_upwind_mms_conv_study_f90_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms_f90" "sediment_upwind_mms_conv_study.yaml")
set_tests_properties(sediment_upwind_mms_conv_study_f90_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;28;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_upwind_mms_conv_study_c_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms" "sediment_upwind_mms_conv_study.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_upwind_mms_conv_study_c_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;28;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_upwind_mms_conv_study_f90_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_mms_f90" "sediment_upwind_mms_conv_study.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_upwind_mms_conv_study_f90_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;28;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_c_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore" "sediment.yaml")
set_tests_properties(sediment_c_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;42;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_f90_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_f90" "sediment.yaml")
set_tests_properties(sediment_f90_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;42;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_c_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore" "sediment.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_c_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;42;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_f90_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore_f90" "sediment.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_f90_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;42;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_ic_filec_np_2_basic "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore" "sediment_ic_file.yaml")
set_tests_properties(sediment_ic_filec_np_2_basic PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;57;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
add_test(sediment_ic_filec_np_2_ceed "/Users/wsugiarta/Documents/github/petsc/arch-opt/bin/mpiexec" "--oversubscribe" "-n" "2" "/Users/wsugiarta/Documents/github/RDycore/build_opt/driver/tests/../rdycore" "sediment_ic_file.yaml" "-ceed" "/cpu/self")
set_tests_properties(sediment_ic_filec_np_2_ceed PROPERTIES  _BACKTRACE_TRIPLES "/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;57;add_test;/Users/wsugiarta/Documents/github/RDycore/driver/tests/sediment/CMakeLists.txt;0;")
