// This file was generated by CMake using cmake/generate_cyaml_sediment_fields.cmake.
// PLEASE DO NOT EDIT DIRECTLY -- change MAX_NUM_SEDIMENT_CLASSES and rerun CMake.

// This macro is used in region_condition_spec_fields_schema in yaml_input.c
#define CYAML_REGION_CONDITION_SPEC_SEDIMENT_FIELDS \
    CYAML_FIELD_STRING("c0", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, sediments[0], 0), \
    CYAML_FIELD_STRING("c1", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, sediments[1], 0), \
    CYAML_FIELD_STRING("c2", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, sediments[2], 0), \
    CYAML_FIELD_STRING("c3", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, sediments[3], 0), \
    CYAML_FIELD_STRING("c4", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, sediments[4], 0), \

// This macro is used in sediment_conditions_fields_schema in yaml_input.c
#define CYAML_SEDIMENT_CONDITION_COMPONENT_FIELDS \
    CYAML_FIELD_MAPPING("c0", CYAML_FLAG_OPTIONAL, RDySedimentCondition, classes[0], component_fields_schema), \
    CYAML_FIELD_MAPPING("c1", CYAML_FLAG_OPTIONAL, RDySedimentCondition, classes[1], component_fields_schema), \
    CYAML_FIELD_MAPPING("c2", CYAML_FLAG_OPTIONAL, RDySedimentCondition, classes[2], component_fields_schema), \
    CYAML_FIELD_MAPPING("c3", CYAML_FLAG_OPTIONAL, RDySedimentCondition, classes[3], component_fields_schema), \
    CYAML_FIELD_MAPPING("c4", CYAML_FLAG_OPTIONAL, RDySedimentCondition, classes[4], component_fields_schema), \

// This macro is used in mms_sediment_fields_schema in yaml_input.c
#define CYAML_MMS_SEDIMENT_FIELDS \
    CYAML_FIELD_STRING("c0", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.c[0], 0), \
    CYAML_FIELD_STRING("dc0dx", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdx[0], 0), \
    CYAML_FIELD_STRING("dc0dy", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdy[0], 0), \
    CYAML_FIELD_STRING("dc0dt", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdt[0], 0), \
    CYAML_FIELD_STRING("c1", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.c[1], 0), \
    CYAML_FIELD_STRING("dc1dx", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdx[1], 0), \
    CYAML_FIELD_STRING("dc1dy", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdy[1], 0), \
    CYAML_FIELD_STRING("dc1dt", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdt[1], 0), \
    CYAML_FIELD_STRING("c2", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.c[2], 0), \
    CYAML_FIELD_STRING("dc2dx", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdx[2], 0), \
    CYAML_FIELD_STRING("dc2dy", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdy[2], 0), \
    CYAML_FIELD_STRING("dc2dt", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdt[2], 0), \
    CYAML_FIELD_STRING("c3", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.c[3], 0), \
    CYAML_FIELD_STRING("dc3dx", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdx[3], 0), \
    CYAML_FIELD_STRING("dc3dy", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdy[3], 0), \
    CYAML_FIELD_STRING("dc3dt", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdt[3], 0), \
    CYAML_FIELD_STRING("c4", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.c[4], 0), \
    CYAML_FIELD_STRING("dc4dx", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdx[4], 0), \
    CYAML_FIELD_STRING("dc4dy", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdy[4], 0), \
    CYAML_FIELD_STRING("dc4dt", CYAML_FLAG_OPTIONAL, RDyMMSSedimentSolutions, expressions.dcdt[4], 0), \

// This macro is used in mms_convergence_rates_fields_schema in yaml_input.c
#define CYAML_MMS_CONVERGENCE_RATES_SEDIMENT_FIELDS \
    CYAML_FIELD_MAPPING("c0", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[0], mms_error_norms_fields_schema), \
    CYAML_FIELD_MAPPING("c1", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[1], mms_error_norms_fields_schema), \
    CYAML_FIELD_MAPPING("c2", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[2], mms_error_norms_fields_schema), \
    CYAML_FIELD_MAPPING("c3", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[3], mms_error_norms_fields_schema), \
    CYAML_FIELD_MAPPING("c4", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[4], mms_error_norms_fields_schema), \

