#!/usr/bin/env python3
"""Map Harvey USGS gauges to Houston1km mesh cells.

The Houston1km mesh is in EPSG:32610 (WGS 84 / UTM zone 10N) -- the
California zone, used ~27 degrees east of its central meridian. This is
established from the mesh-generation pipeline (donghuix/OFMmesh, ex1 =
"Houston Harvey Flooding": `proj = projcrs(32610)` in read_data.m et al.)
and verified by inverse-projecting the mesh bbox onto west Houston
(Addicks/Barker reservoirs -> Buffalo Bayou -> ship-channel Turning Basin).
Beware: at this longitude offset the projection carries ~9% length and
~19% area inflation and a ~14.5 deg grid rotation relative to true north.

Reads houston_gauges.csv (site_no, lon, lat, gage_datum_ft, datum,
station, has_stage_ts) and the TRI3 Exodus mesh, locates each gauge by
point-in-triangle test, and writes:
  - houston_gauges_cells.csv: gauges inside the mesh, with the containing
    cell's natural ID (mesh-file order, 0-based -- the numbering
    observations.sites.cells expects), projected coords, and the cell's
    mean bed elevation for datum QC.
  - observations_sites_snippet.yaml: ready-to-paste sites.cells list.

Usage: python3 map_gauges_to_cells.py [mesh.exo] [gauges.csv] [outdir]
Requires: numpy, netCDF4, pyproj.
"""

import csv
import sys
from pathlib import Path

import numpy as np
from netCDF4 import Dataset
from pyproj import Transformer

HERE = Path(__file__).parent
MESH = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "../../share/meshes/Houston1km_with_z.exo"
GAUGES = Path(sys.argv[2]) if len(sys.argv) > 2 else HERE / "houston_gauges.csv"
OUTDIR = Path(sys.argv[3]) if len(sys.argv) > 3 else HERE

MESH_CRS = "EPSG:32610"
FT_TO_M = 0.3048


def main():
    with Dataset(MESH) as nc:
        x = np.array(nc.variables["coordx"][:])
        y = np.array(nc.variables["coordy"][:])
        z = np.array(nc.variables["coordz"][:])
        conn = np.array(nc.variables["connect1"][:]) - 1  # 1-based -> 0-based

    # triangle vertex arrays, one row per cell in natural (mesh-file) order
    xa, ya = x[conn[:, 0]], y[conn[:, 0]]
    xb, yb = x[conn[:, 1]], y[conn[:, 1]]
    xc, yc = x[conn[:, 2]], y[conn[:, 2]]
    zcell = z[conn].mean(axis=1)

    t = Transformer.from_crs("EPSG:4326", MESH_CRS, always_xy=True)

    rows_in, rows_out = [], []
    with open(GAUGES) as f:
        for g in csv.DictReader(f):
            lon, lat = float(g["lon"]), float(g["lat"])
            px, py = t.transform(lon, lat)
            # signed areas of the sub-triangles (barycentric sign test);
            # tolerance admits gauges within ~1 m of an edge
            d1 = (xa - px) * (yb - py) - (xb - px) * (ya - py)
            d2 = (xb - px) * (yc - py) - (xc - px) * (yb - py)
            d3 = (xc - px) * (ya - py) - (xa - px) * (yc - py)
            tol = 1.0  # m^2-scale slack for on-edge points
            inside = ((d1 >= -tol) & (d2 >= -tol) & (d3 >= -tol)) | ((d1 <= tol) & (d2 <= tol) & (d3 <= tol))
            hits = np.flatnonzero(inside)
            rec = dict(g, x_utm10=f"{px:.1f}", y_utm10=f"{py:.1f}")
            if hits.size:
                cell = int(hits[0])
                rec["cell"] = cell
                rec["cell_z_m"] = f"{zcell[cell]:.2f}"
                rec["gage_datum_m"] = f"{float(g['gage_datum_ft']) * FT_TO_M:.2f}"
                rows_in.append(rec)
            else:
                rows_out.append(rec)

    out_csv = OUTDIR / "houston_gauges_cells.csv"
    fields = ["site_no", "lon", "lat", "x_utm10", "y_utm10", "cell", "cell_z_m", "gage_datum_ft", "gage_datum_m", "datum", "station", "has_stage_ts"]
    with open(out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows_in)

    with_ts = [r for r in rows_in if r["has_stage_ts"] == "True"]
    out_yaml = OUTDIR / "observations_sites_snippet.yaml"
    with open(out_yaml, "w") as f:
        f.write("# gauges with Harvey stage series inside the Houston1km mesh\n")
        f.write("# (cell = natural ID; generated by map_gauges_to_cells.py)\n")
        f.write("      sites:\n        cells: [")
        f.write(", ".join(str(r["cell"]) for r in with_ts))
        f.write("]\n")

    print(f"gauges inside mesh: {len(rows_in)} of {len(rows_in) + len(rows_out)} ({len(with_ts)} with stage series)")
    for r in rows_in:
        mark = "*" if r["has_stage_ts"] == "True" else " "
        print(f" {mark} {r['site_no']} cell {r['cell']:5d}  cell_z {r['cell_z_m']:>7s} m  datum {r['gage_datum_m']:>7s} m {r['datum']:7s} {r['station'][:48]}")
    print(f"wrote {out_csv.name}, {out_yaml.name}")


if __name__ == "__main__":
    main()
