# This function extracts a variable from the petscvariables file
function(extract_petsc_variable varname var)
  file(READ "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables" petscvariables)
  string(FIND ${petscvariables} "\nMPIEXEC = " start)
  if (${start} EQUAL -1)
    message(FATAL_ERROR "Could not extract ${var_name} from PETSc. Please set ${var_name} using -D${var_name}=...")
  endif()
  math(EXPR start "${start} + 11")
  string(SUBSTRING ${petscvariables} ${start} -1 petsc_var)
  string(FIND ${petsc_var} " " space)
  string(FIND ${petsc_var} "\n" newline)
  if (space LESS newline)
    string(SUBSTRING ${petsc_var} 0 ${space} var)
  else()
    string(SUBSTRING ${petsc_var} 0 ${newline} var)
  endif()
  message(STATUS "Using PETSc-provided ${varname}: ${var}")
  set(${varname} ${var} PARENT_SCOPE)
endfunction()
