# This CMake function generates a file named cyaml_tracers.h in the include/ folder within
# your build directory. The file defines tracer fields for our YAML schema based on the build
# parameter MAX_NUM_TRACERS. See related comments in src/yaml_input.c.

function(generate_cyaml_tracer_fields)
  math(EXPR N "${MAX_NUM_TRACERS} - 1") # loop variable
  list(APPEND lines "// This file was generated by CMake using cmake/generate_cyaml_tracers.cmake.")
  list(APPEND lines "// PLEASE DO NOT EDIT DIRECTLY -- change MAX_NUM_TRACERS and rerun CMake.")
  list(APPEND lines "")

  list(APPEND lines "// This macro is used in region_condition_spec_tracers_schema in yaml_input.c")
  list(APPEND lines "#define CYAML_REGION_CONDITION_SPEC_TRACERS \\")
  foreach(i RANGE ${N})
    list(APPEND lines "    CYAML_FIELD_STRING(\"c${i}\", CYAML_FLAG_OPTIONAL, RDyRegionConditionSpec, tracer[${i}], 0), \\")
  endforeach()
  list(APPEND lines "")

  list(APPEND lines "// This macro is used in mms_fields_schema in yaml_input.c")
  list(APPEND lines "#define CYAML_MMS_TRACERS \\")
  foreach(i RANGE ${N})
    list(APPEND lines "    CYAML_FIELD_STRING(\"c${i}\", CYAML_FLAG_OPTIONAL, RDyMMSTracerSolutions, expressions.c[${i}], 0), \\")
    list(APPEND lines "    CYAML_FIELD_STRING(\"dc${i}dx\", CYAML_FLAG_OPTIONAL, RDyMMSTracerSolutions, expressions.dcdx[${i}], 0), \\")
    list(APPEND lines "    CYAML_FIELD_STRING(\"dc${i}dy\", CYAML_FLAG_OPTIONAL, RDyMMSTracerSolutions, expressions.dcdy[${i}], 0), \\")
    list(APPEND lines "    CYAML_FIELD_STRING(\"dc${i}dt\", CYAML_FLAG_OPTIONAL, RDyMMSTracerSolutions, expressions.dcdt[${i}], 0), \\")
  endforeach()
  list(APPEND lines "")

  list(APPEND lines "// This macro is used in mms_convergence_rates_fields_schema in yaml_input.c")
  list(APPEND lines "#define CYAML_MMS_CONVERGENCE_RATES_TRACERS \\")
  foreach(i RANGE ${N})
    list(APPEND lines "    CYAML_FIELD_MAPPING(\"c${i}\", CYAML_FLAG_OPTIONAL, RDyMMSConvergenceRates, c[${i}], mms_error_norms_fields_schema), \\")
  endforeach()
  list(APPEND lines "")
  list(APPEND lines "")

  # write our lines list to a newline-delimited string and then write the file
  string(REPLACE ";" "\n" source "${lines}")
  set(header_file ${PROJECT_BINARY_DIR}/include/cyaml_tracers.h)
  message(STATUS "Generating ${header_file}")
  file(WRITE ${header_file} ${source})
endfunction()
