name: auto_test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds RDycore and runs our test suite.
  build:
    runs-on: ${{ matrix.os }}
    container: coherellc/rdycore-petsc:v3.18.1

    # A build matrix storing all desired configurations.
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        build-type: [Debug] #, Release]

    # Steps for building and running tests.
    steps:

    - name: Checking out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

    - name: Configuring RDycore (${{ matrix.build-type }})
      run: |
        cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
        -DCODE_COVERAGE=ON \
        -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Building RDycore (${{ matrix.build-type }})
      run: |
        grep PETSC_VERSION_GIT $PETSC_DIR/include/petscconf.h | sed -e s/#define\ //g
        cd build
        make -j

    - name: Running tests (${{ matrix.build-type }})
      run: |
        set +e # disable "fast fail" (continue on test failures to show output)
        cd build
        make test
        failed=$?
        if [ $failed -ne 0 ]; then
          cat Testing/Temporary/LastTest.log
        fi
        test $failed -eq 0

    - name: Evaluating test coverage
      #if: github.event.pull_request.draft == false # skip for draft PRs
      run: |
        make ccov-all
        cp ccov/all-merged.info coverage.info
        lcov --list coverage.info # debug info
        curl -s https://codecov.io/bash > .codecov
        chmod +x .codecov
        ./.codecov
        #bash <(curl -s https://codecov.io/bash  -f coverage.info)
