name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: C code formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: 'driver include src'
        extensions: 'h,c'
        clangFormatVersion: 14
