name: Build and deploy gh-pages branch with Mkdocs

on:
  # Runs every time main branch is updated
  push:
    branches: ["main"]
  # Runs every time a PR is open against main
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  # Prevent 2+ copies of this workflow from running concurrently
  group: rdycore-docs-action

jobs:
  Build-and-Deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0 # Needed, or else gh-pages won't be fetched, and push rejected
          submodules: false # speeds up clone and not building anything in submodules
      - name: Show action trigger
        run: echo "= The job was automatically triggered by a ${{github.event_name}} event."
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"
      - name: Install python deps
        run: python3 -m pip install mkdocs-material pymdown-extensions mkdocs-monorepo-plugin mdutils mkdocs-bibtex
      # build every time (PR or push to main)
      - name: Build
        run: mkdocs build --strict --verbose
      # deploy only when it is a push
      - if: ${{ github.event_name == 'push' }}
        name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Do not remove existing pr-preview pages
          clean-exclude: pr-preview
          folder: ./site/
      # If it's a PR from within the same repo, deploy to a preview page
      # For security reasons, PRs from forks cannot write into gh-pages for now
      - if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        name: Preview docs
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
